/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import controladores.Fabrica;
import controladores.ISistema;
import logica.ActividadTuristica;
import logica.Paquete;
import logica.SalidasTuristicas;
import controladores.Sistema;
import datatypes.DataActividad;
import datatypes.DataUsuario;
import datatypes.DataSalida;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import logica.Departamento;


/**
 *
 * @author amadeus
 */
public class AltaSalidaTuristica extends javax.swing.JInternalFrame {
    ISistema sys;
    String nombreDepto, nombreAct, correoProv, descripcion, nombreSal, lugar, act;
    Integer cantidad;
    LocalDate fechaS;
    LocalDate fechaA;
    boolean excepcionLanzada=false;
    boolean excepcionLanzada2=false;
    String[] strings;
    String[] strings2=new String[]{};
    String[] strings3=new String[]{};
    String[] strings4=new String[]{};
    ActividadTuristica acts;
    /**
     * Creates new form ConsultaActividad
     */
    public AltaSalidaTuristica() {
        sys = new Fabrica().getSistema();
        strings = sys.listarDepartamentos();
        //strings2 = sys.listarDepartamentos();
        initComponents();
       // this.setSize(420, 420);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(strings));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, -1));

        jLabel2.setText("Seleccione el Departamento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, 20));

        jLabel1.setText("Seleccione una Actividad de ese Departamento:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 360, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(strings2));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 140, -1));

        jLabel5.setText("Datos de la Salida a ingresar:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel7.setText("Lugar:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel3.setText("Cant. maxima de turistas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel8.setText("Fecha Salida:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel9.setText("Fecha Alta:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 180, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 190, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 80, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 150, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 160, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 250, 20));

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 110, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        strings2 = sys.listarActividadesDeptoArreglo(jComboBox1.getSelectedItem().toString());
        actualizarComboBox2Model();
        jLabel3.setVisible(true);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
      acts=sys.selectActividad(jComboBox2.getSelectedItem().toString());
      strings3 = sys.listarSalidasActividad(jComboBox2.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            SalidasTuristicas s;
            excepcionLanzada=false;
            excepcionLanzada2=false;
            jLabel10.setVisible(true);
            nombreDepto=jComboBox1.getSelectedItem().toString();
            nombreAct=jComboBox2.getSelectedItem().toString();
            nombreSal=jTextField1.getText();
            lugar=jTextField2.getText();
            boolean esta=false;
            for(int i=0;i<strings3.length;i++){
                if(acts.getSalidaByNombre(strings3[i]).getNombreSalida()==nombreSal){
                    System.out.print(acts.getSalidaByNombre(strings3[i]).getNombreSalida()+"  "+nombreSal);
                    esta=true;
                }  
            }
            
            try {
                cantidad=Integer.parseInt(jTextField3.getText());
            } catch (NumberFormatException e) {
                jLabel10.setText("Debe poner solo numeros en la cantidad");
                jLabel10.setVisible(true);
                excepcionLanzada = true;
            }      
            String cantidadTexto = jTextField3.getText();
            if (!cantidadTexto.isEmpty() && cantidadTexto.chars().allMatch(Character::isDigit)) {
                cantidad = Integer.parseInt(cantidadTexto);
            } else {
                jLabel10.setText("Debe ingresar solo números en la cantidad");
                jLabel10.setVisible(true);
                excepcionLanzada = true;
            }
            
            try {
                fechaA = LocalDate.parse(jTextField5.getText());
            } catch (DateTimeParseException ex) {
                jLabel10.setText("El formato de fecha es incorrecto. Debe ser yyyy-MM-dd.");
                jLabel10.setVisible(true);
                excepcionLanzada2 = true;
            }
            
            try {
                fechaS = LocalDate.parse(jTextField4.getText());
            } catch (DateTimeParseException ex) {
                jLabel10.setText("El formato de fecha es incorrecto. Debe ser yyyy-MM-dd.");
                jLabel10.setVisible(true);
                excepcionLanzada2 = true;
            }

            if(!(excepcionLanzada || excepcionLanzada2)){
                if(nombreSal.isEmpty()||lugar.isEmpty()||cantidad==null||fechaS==null||fechaA==null){
                    jLabel10.setText("Debe llenar todos los campos para confirmar");
                    jLabel10.setVisible(true);
                }
                else{ 
                    if(esta){
                    jLabel10.setText("Salida ya ingresada, ingrese otra salida o ciere la ventana");
                    jLabel10.setVisible(true);
                    }
                    else{
                        sys.AltaSalidaTuristicaDepto(nombreSal, lugar, cantidad, fechaS, fechaA, nombreAct,nombreDepto);
                        jLabel10.setText("Salida Registrada con Exito");
                        jLabel10.setVisible(true);
                    }
                }
            }
    }//GEN-LAST:event_jButton1ActionPerformed
  
private void actualizarComboBox2Model() {
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(strings2);
    jComboBox2.setModel(model);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
