/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import controladores.Fabrica;
import controladores.ISistema;
import datatypes.DataActividad;
import datatypes.DataSalida;

/**
 *
 * @author samuel
 */
public class ConsultaSalidaTur extends javax.swing.JInternalFrame {

    ISistema sys;
    /**
     * Creates new form ConsultaSalidaTur
     */
    String nombreDepto, nombreAct, nombreSalida;

    public ConsultaSalidaTur() {

        sys = new Fabrica().getSistema();
        initComponents();
                comboboxDepto.setSelectedItem(null);
comboboxAct.setSelectedItem(null);
comboBoxSalida.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textoDatosSalida = new javax.swing.JTextArea();
        comboboxDepto = new javax.swing.JComboBox<>();
        comboboxAct = new javax.swing.JComboBox<>();
        comboBoxSalida = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de Salida");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccione el Departamento de la Actividad");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 430, 20));

        textoDatosSalida.setEditable(false);
        textoDatosSalida.setColumns(20);
        textoDatosSalida.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        textoDatosSalida.setRows(5);
        jScrollPane4.setViewportView(textoDatosSalida);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 560, 190));

        comboboxDepto.setModel(new javax.swing.DefaultComboBoxModel<>(sys.listarDepartamentos()));
        comboboxDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxDeptoActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 390, -1));

        comboboxAct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        comboboxAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActActionPerformed(evt);
            }
        });
        getContentPane().add(comboboxAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 390, -1));

        comboBoxSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        comboBoxSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 390, -1));

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxDeptoActionPerformed
            // TODO add your handling code here:
                            if (comboboxDepto.getSelectedItem() == null) {
            return;
        }
        nombreDepto =  (String) comboboxDepto.getSelectedItem();// this.
        //listaPrincipal.setVisible(false);
        comboBoxSalida.setSelectedItem(null);

        sys.selectDepartamento(nombreDepto);
        jLabel1.setText("Seleccione la actividad de " + nombreDepto);
        DataActividad[] acts = sys.listarActividadesDepto(nombreDepto);
        if (acts.length == 0) {
            jLabel1.setText("No hay actividades para ese departamento" );
        }
        String strings[] = new String[acts.length];
        for (int i = 0; i < acts.length; i++) {
            strings[i] = acts[i].getNombre();
        }

        comboboxAct.setModel(new javax.swing.DefaultComboBoxModel<>(strings));
        comboboxAct.setSelectedItem(null);
    }//GEN-LAST:event_comboboxDeptoActionPerformed

    private void comboboxActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActActionPerformed
  if (comboboxAct.getSelectedItem() == null) {
            return;
        }
        nombreAct = (String) comboboxAct.getSelectedItem();
        jLabel1.setText("Seleccione la salida de " + nombreAct);


        String[] salidasAct = sys.listarSalidasActividad(nombreAct);
        if(salidasAct.length == 0){
        jLabel1.setText("No hay salidas para la actividad");
        }
        comboBoxSalida.setModel(new javax.swing.DefaultComboBoxModel<>(salidasAct));
        
        comboBoxSalida.setSelectedItem(null);

     
    }//GEN-LAST:event_comboboxActActionPerformed

    private void comboBoxSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSalidaActionPerformed
        if (comboBoxSalida.getSelectedItem() == null) {
            return;
        }
        nombreSalida = (String) comboBoxSalida.getSelectedItem();
        DataSalida dt = sys.datosSalida(nombreSalida, nombreAct, nombreDepto);
        if (dt == null) {
            return;
        }


        jLabel1.setText("Datos de la salida: " + nombreSalida);

        textoDatosSalida.setText(dt.toString());
        textoDatosSalida.setVisible(true);
    }//GEN-LAST:event_comboBoxSalidaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxSalida;
    private javax.swing.JComboBox<String> comboboxAct;
    private javax.swing.JComboBox<String> comboboxDepto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea textoDatosSalida;
    // End of variables declaration//GEN-END:variables
}
