/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;
import controladores.Fabrica;
import controladores.ISistema;
import logica.ActividadTuristica;
import logica.Paquete;
import logica.SalidasTuristicas;
import controladores.Sistema;
import datatypes.DataActividad;
import datatypes.DataUsuario;
import datatypes.DataSalida;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import logica.Departamento;


/**
 *
 * @author amadeus
 */
public class ConsultaActividad extends javax.swing.JInternalFrame {
    ISistema sys;
    String nombreDepto, nombreAct, correoProv, descripcion, ciudad;
    String[] strings;
    String[] strings2=new String[]{};
    String[] strings3=new String[]{};
    String[] strings4=new String[]{};
    String act;
    ActividadTuristica acts;
    Paquete p=null;
    /**
     * Creates new form ConsultaActividad
     */
    public ConsultaActividad() {
        sys = new Fabrica().getSistema();
        strings = sys.listarDepartamentos();
        //strings2 = sys.listarDepartamentos();
        initComponents();
       // this.setSize(420, 420);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableAct = new javax.swing.JTable();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableAct1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableP = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(strings));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 140, -1));

        jLabel2.setText("Seleccione el Departamento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 220, 20));

        jLabel1.setText("Seleccione una Actividad de ese Departamento:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 360, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(strings2));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 400, 20));

        tableAct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Duracion", "Costo", "Ciudad", "Fecha Alta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableAct);
        if (tableAct.getColumnModel().getColumnCount() > 0) {
            tableAct.getColumnModel().getColumn(0).setResizable(false);
            tableAct.getColumnModel().getColumn(1).setResizable(false);
            tableAct.getColumnModel().getColumn(2).setResizable(false);
            tableAct.getColumnModel().getColumn(3).setResizable(false);
            tableAct.getColumnModel().getColumn(4).setResizable(false);
            tableAct.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 620, 60));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 140, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 160, -1));

        jLabel4.setText("Salidas Turisticas de esa Actividad:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel5.setText("Paquetes  con esa Actividad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        tableAct1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Lugar", "Cant Max", "Fecha Sal", "Fecha Alta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableAct1);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 620, 90));

        tableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Descripcion", "Validez", "Descuento", "Alta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableP);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 620, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        strings2 = sys.listarActividadesDeptoArreglo(jComboBox1.getSelectedItem().toString());
        actualizarComboBox2Model();
        jLabel3.setVisible(true);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
      DefaultTableModel tableModel = (DefaultTableModel) tableAct.getModel(); // Obtén el modelo de la JTable
      if (tableModel.getRowCount() > 0) {
            // Elimina la primera fila (fila en el índice 0)
        tableModel.removeRow(0);
      }
      acts=sys.selectActividad(jComboBox2.getSelectedItem().toString());
      Object [] rowData= {acts.getNombre(),acts.getDescripcion(),acts.getDuracionHoras(),acts.getCostoPorTurista(),acts.getCiudad(),acts.getFechaAlta()};
      tableModel.addRow(rowData);
      
      strings3 = sys.listarSalidasActividad(jComboBox2.getSelectedItem().toString());
      actualizarComboBox3Model();
      
      strings4 = sys.listarPaquetesActArreglo(jComboBox2.getSelectedItem().toString());

      actualizarComboBox4Model();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
         DefaultTableModel tableModel = (DefaultTableModel) tableP.getModel(); // Obtén el modelo de la JTable
        if (tableP.getRowCount() > 0) {
            while (tableModel.getRowCount() > 0) {
                tableModel.removeRow(0); // Elimina la primera fila
            }
        }

        for (int i = 0; i < strings4.length; i++) {
            Paquete p = sys.selectPaquete(strings4[i]); 
            if (p != null) {
                Object[] rowData2 = { p.getNombre_paquete(), p.getDescri(), p.getValidez(), p.getDescuento(), p.getAlta() };
                tableModel.addRow(rowData2); 
            }
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
      DefaultTableModel tableModel = (DefaultTableModel) tableAct1.getModel();
      SalidasTuristicas s;
            while (tableModel.getRowCount() > 0) {
            // Elimina la primera fila (fila en el índice 0)
        tableModel.removeRow(0);
      }
           
      for(int i=0;i<strings3.length;i++){
          s=acts.getSalidaByNombre(strings3[i]); 
          Object [] rowData2= {s.getNombreSalida(),s.getLugar(),s.getCantidadMaximaTuristas(),s.getFechaSalida().toString(),s.getFechaAlta().toString()};
        tableModel.addRow(rowData2); 
      }
    }//GEN-LAST:event_jComboBox3ActionPerformed

private void actualizarComboBox4Model() {
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(strings4);
    jComboBox4.setModel(model);
}
    
    
private void actualizarComboBox3Model() {
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(strings3);
    jComboBox3.setModel(model);
}
    
    
private void actualizarComboBox2Model() {
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(strings2);
    jComboBox2.setModel(model);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tableAct;
    private javax.swing.JTable tableAct1;
    private javax.swing.JTable tableP;
    // End of variables declaration//GEN-END:variables
}
