/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import controladores.Fabrica;
import controladores.ISistema;
import javax.swing.JOptionPane;

/**
 *
 * @author samuel
 */
public class EstadoActTuristica extends javax.swing.JInternalFrame {

    ISistema sys = new Fabrica().getSistema();
    String[] acts = sys.listarActividadesEnEspera();
    String actSeleccionada = "";

    /**
     * Creates new form EstadoActTuristica
     */
    public EstadoActTuristica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxAct = new javax.swing.JComboBox<>();
        botonAceptar = new javax.swing.JButton();
        botonRechazar = new javax.swing.JButton();
        mensajeLabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Confirmar / Rechazar Actividad");

        comboBoxAct.setModel(new javax.swing.DefaultComboBoxModel<>(acts));
        comboBoxAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.setEnabled(false);
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonRechazar.setText("Rechazar");
        botonRechazar.setEnabled(false);
        botonRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRechazarActionPerformed(evt);
            }
        });

        mensajeLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        mensajeLabel.setText("Seleccione la actividad");
        mensajeLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mensajeLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRechazar)
                        .addGap(74, 74, 74))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxAct, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboBoxAct, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(mensajeLabel)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonRechazar))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActActionPerformed

        actSeleccionada = comboBoxAct.getSelectedItem().toString();
        mensajeLabel.setText("Actividad: " + actSeleccionada + " seleccionada");
        botonAceptar.setEnabled(true);
        botonRechazar.setEnabled(true);
    }//GEN-LAST:event_comboBoxActActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        sys.aceptarActividad(actSeleccionada);
        sacarActComboBox(comboBoxAct.getSelectedIndex());
        JOptionPane.showMessageDialog(null, "Actividad " + actSeleccionada + " aceptada");
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRechazarActionPerformed
        sys.rechazarActividad(actSeleccionada);
        
        sacarActComboBox(comboBoxAct.getSelectedIndex());
        JOptionPane.showMessageDialog(null, "Actividad " + actSeleccionada + " rechazada");
    }//GEN-LAST:event_botonRechazarActionPerformed

    private void sacarActComboBox(int indice) {
        String[] nuevasAct = new String[acts.length - 1];
        int i = 0;
        int j = 0;
        for (String actNombre : acts) {
            if (i != indice) {
                nuevasAct[j] = acts[i];
                j++;
            }
            i++;
        }
        acts = nuevasAct;
                comboBoxAct.setModel(new javax.swing.DefaultComboBoxModel<>(acts));
                actSeleccionada = "";
                botonAceptar.setEnabled(false);
                
                botonRechazar.setEnabled(false);
                mensajeLabel.setText("Seleccione una actividad");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonRechazar;
    private javax.swing.JComboBox<String> comboBoxAct;
    private javax.swing.JLabel mensajeLabel;
    // End of variables declaration//GEN-END:variables
}
