/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import controladores.Fabrica;
import controladores.ISistema;
import datatypes.DataActividad;
import datatypes.DataSalida;
import datatypes.DataUsuario;
import java.time.LocalDate;

/**
 *
 * @author samuel
 */
public class InscripcionSalidaTur extends javax.swing.JInternalFrame {

    ISistema sys;
    /**
     * Creates new form ConsultaSalidaTur
     */
    String nombreDepto, nombreAct, nombreSalida;
    String mailTurista;
    int cantidadTur;

    public InscripcionSalidaTur() {

        sys = new Fabrica().getSistema();
        initComponents();
        comboboxDepto.setSelectedItem(null);
        comboboxTuristas.setSelectedItem(null);
        comboboxAct.setSelectedItem(null);
        comboBoxSalida.setSelectedItem(null);

        //    panelInscripcion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panelInscripcion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cantField = new javax.swing.JTextField();
        turistaLabel = new javax.swing.JLabel();
        salidaLabel = new javax.swing.JLabel();
        actividadLabel = new javax.swing.JLabel();
        confirmarButton = new javax.swing.JButton();
        labelMensaje = new javax.swing.JLabel();
        mensajeLabel = new javax.swing.JLabel();
        comboboxTuristas = new javax.swing.JComboBox<>();
        comboboxDepto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        comboboxAct = new javax.swing.JComboBox<>();
        comboBoxSalida = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inscripcion a Salida Turística");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccione el Departamento de la Actividad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 450, 20));

        panelInscripcion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Cantidad de turistas");
        panelInscripcion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        cantField.setText("1");
        cantField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantFieldActionPerformed(evt);
            }
        });
        panelInscripcion.add(cantField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 120, 30));

        turistaLabel.setText("Turista");
        panelInscripcion.add(turistaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, 30));

        salidaLabel.setText("Salida");
        panelInscripcion.add(salidaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        actividadLabel.setText("Departamento");
        panelInscripcion.add(actividadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        confirmarButton.setText("Confirmar Inscripcion");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });
        panelInscripcion.add(confirmarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        labelMensaje.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        labelMensaje.setForeground(new java.awt.Color(255, 255, 255));
        panelInscripcion.add(labelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        mensajeLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        mensajeLabel.setForeground(new java.awt.Color(0, 0, 0));
        mensajeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mensajeLabel.setText("             ");
        panelInscripcion.add(mensajeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 360, 40));

        DataUsuario[] dataTuristas = sys.listarTuristas();
        String[] nombresTur = new String[dataTuristas.length];
        for(int i = 0; i< dataTuristas.length;i++){
            nombresTur[i] = dataTuristas[i].getCorreo() ;
        }
        comboboxTuristas.setModel(new javax.swing.DefaultComboBoxModel<>(nombresTur));
        comboboxTuristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxTuristasActionPerformed(evt);
            }
        });
        panelInscripcion.add(comboboxTuristas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 210, -1));

        comboboxDepto.setModel(new javax.swing.DefaultComboBoxModel<>(sys.listarDepartamentos()));
        comboboxDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxDeptoActionPerformed(evt);
            }
        });
        panelInscripcion.add(comboboxDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 210, -1));

        jLabel3.setText("Actividad");
        panelInscripcion.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        comboboxAct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        comboboxAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActActionPerformed(evt);
            }
        });
        panelInscripcion.add(comboboxAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 210, -1));

        comboBoxSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        comboBoxSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSalidaActionPerformed(evt);
            }
        });
        panelInscripcion.add(comboBoxSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelInscripcion.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 140, -1));

        getContentPane().add(panelInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 420, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantFieldActionPerformed

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
               nombreSalida = (String) comboBoxSalida.getSelectedItem();
        try {
            cantidadTur = Integer.parseInt(cantField.getText());
        } catch (Exception e) {
            mensajeLabel.setText("Cantidad no es un número válido");
            return;
        }
        if (mailTurista.isEmpty() || nombreSalida.isEmpty() || cantidadTur == 0) {

            mensajeLabel.setText("Faltan campos por rellenar");
            if (cantidadTur <= 0) {
                mensajeLabel.setText("La cantidad de turistas debe ser mayor a 0");
            }
            return;
        }

        if (sys.inscripcionSalida(mailTurista, nombreSalida, cantidadTur, LocalDate.now())) {

            sys.confirmarInscripcion(cantidadTur, 0);
            mensajeLabel.setText("Inscripcion registrada correctamente");
        } else {
            if (sys.estaInscritoTuristaSalida(mailTurista, nombreSalida)) {

                mensajeLabel.setText("Turista ya inscrito para esa salida");
            } else if (sys.excedeLimiteInscripcion(nombreSalida, cantidadTur)) {

                mensajeLabel.setText("No quedan suficientes cupos en la salida");
            } else {
                mensajeLabel.setText("Error al registrar la salida");
            }
        }
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void comboboxTuristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxTuristasActionPerformed
        if (comboboxTuristas.getSelectedItem() == null) {
            return;
        }
        mailTurista = (String) comboboxTuristas.getSelectedItem();
    }//GEN-LAST:event_comboboxTuristasActionPerformed

    private void comboboxDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxDeptoActionPerformed
        if (comboboxDepto.getSelectedItem() == null) {
            return;
        }
        comboBoxSalida.setSelectedItem(null);
        nombreDepto = (String) comboboxDepto.getSelectedItem();
        sys.selectDepartamento(nombreDepto);
        jLabel1.setText("Seleccione la actividad de " + nombreDepto);
        DataActividad[] acts = sys.listarActividadesDepto(nombreDepto);
        if (acts.length == 0) {
            jLabel1.setText("No hay actividades para ese departamento");
        }
        String strings[] = new String[acts.length];
        for (int i = 0; i < acts.length; i++) {
            strings[i] = acts[i].getNombre();
        }

        comboboxAct.setModel(new javax.swing.DefaultComboBoxModel<>(strings));

        comboboxAct.setSelectedItem(null);
    }//GEN-LAST:event_comboboxDeptoActionPerformed

    private void comboboxActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActActionPerformed
        if (comboboxAct.getSelectedItem() == null) {
            return;
        }
        nombreAct = (String) comboboxAct.getSelectedItem();
        jLabel1.setText("Seleccione la salida de " + nombreAct);

        String[] salidasAct = sys.listarSalidasActividad(nombreAct);
        if (salidasAct.length == 0) {
            jLabel1.setText("No hay salidas para la actividad");
        }
        comboBoxSalida.setModel(new javax.swing.DefaultComboBoxModel<>(salidasAct));

        comboBoxSalida.setSelectedItem(null);

    }//GEN-LAST:event_comboboxActActionPerformed

    private void comboBoxSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSalidaActionPerformed
        if (comboBoxSalida.getSelectedItem() == null) {
            return;
        }
        nombreSalida = (String) comboBoxSalida.getSelectedItem();

    }//GEN-LAST:event_comboBoxSalidaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actividadLabel;
    private javax.swing.JTextField cantField;
    private javax.swing.JComboBox<String> comboBoxSalida;
    private javax.swing.JComboBox<String> comboboxAct;
    private javax.swing.JComboBox<String> comboboxDepto;
    private javax.swing.JComboBox<String> comboboxTuristas;
    private javax.swing.JButton confirmarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel mensajeLabel;
    private javax.swing.JPanel panelInscripcion;
    private javax.swing.JLabel salidaLabel;
    private javax.swing.JLabel turistaLabel;
    // End of variables declaration//GEN-END:variables
}
