/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import controladores.Fabrica;
import controladores.ISistema;
import excepciones.UsuarioRepetidoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author amadeus
 */
public class Principal extends javax.swing.JFrame {

    ISistema sys;

    /**
     * Creates new form Principal
     */
    public Principal() {
        sys = new Fabrica().getSistema();
        initComponents();
        this.setSize(800, 800);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        RegistrarCategoria = new javax.swing.JMenu();
        itemAltaUsuario = new javax.swing.JMenuItem();
        itemAltaActividad = new javax.swing.JMenuItem();
        itemAltaSalida = new javax.swing.JMenuItem();
        itemInscripcionSalida = new javax.swing.JMenuItem();
        itemAltaPaquete = new javax.swing.JMenuItem();
        itemAgregarActPaquete = new javax.swing.JMenuItem();
        itemAltaDepartamento = new javax.swing.JMenuItem();
        itemModificarUsuario = new javax.swing.JMenuItem();
        CambiarEstadoActividad = new javax.swing.JMenuItem();
        itemRegistrarCategoria = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemConsultaUsuario = new javax.swing.JMenuItem();
        itemConsultaActividad = new javax.swing.JMenuItem();
        itemConsultaPaquete = new javax.swing.JMenuItem();
        itemConsultaSalida = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        menuSistema.setText("Sistema");

        jMenuItem2.setText("Cargar datos de prueba");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuSistema.add(jMenuItem2);

        jMenuBar1.add(menuSistema);

        RegistrarCategoria.setText("Registros");
        RegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarCategoriaActionPerformed(evt);
            }
        });

        itemAltaUsuario.setText("Alta Usuario");
        itemAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAltaUsuarioActionPerformed(evt);
            }
        });
        RegistrarCategoria.add(itemAltaUsuario);

        itemAltaActividad.setText("Alta de Actividad Turística");
        itemAltaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAltaActividadActionPerformed(evt);
            }
        });
        RegistrarCategoria.add(itemAltaActividad);

        itemAltaSalida.setText("Alta de Salida Turística");
        itemAltaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAltaSalidaActionPerformed(evt);
            }
        });
        RegistrarCategoria.add(itemAltaSalida);

        itemInscripcionSalida.setText("Inscripción a Salida Turística");
        itemInscripcionSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInscripcionSalidaActionPerformed(evt);
            }
        });
        RegistrarCategoria.add(itemInscripcionSalida);

        itemAltaPaquete.setText("Crear Paquete de Actividades Turísticas");
        itemAltaPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAltaPaqueteActionPerformed(evt);
            }
        });
        RegistrarCategoria.add(itemAltaPaquete);

        itemAgregarActPaquete.setText("Agregar Actividad Turística a Paquete");
        itemAgregarActPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarActPaqueteActionPerformed(evt);
            }
        });
        RegistrarCategoria.add(itemAgregarActPaquete);

        itemAltaDepartamento.setText("Alta de Departamento");
        itemAltaDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAltaDepartamentoActionPerformed(evt);
            }
        });
        RegistrarCategoria.add(itemAltaDepartamento);

        itemModificarUsuario.setText("Modificar Datos de Usuarios");
        itemModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModificarUsuarioActionPerformed(evt);
            }
        });
        RegistrarCategoria.add(itemModificarUsuario);

        CambiarEstadoActividad.setText("Aceptar / Rechazar Actividad");
        CambiarEstadoActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarEstadoActividadActionPerformed(evt);
            }
        });
        RegistrarCategoria.add(CambiarEstadoActividad);

        itemRegistrarCategoria.setText("Registrar Categoría");
        itemRegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarCategoriaActionPerformed(evt);
            }
        });
        RegistrarCategoria.add(itemRegistrarCategoria);

        jMenuBar1.add(RegistrarCategoria);

        jMenu1.setText("Consultas");

        itemConsultaUsuario.setText("Consulta de Usuario");
        itemConsultaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultaUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(itemConsultaUsuario);

        itemConsultaActividad.setText("Consulta de Actividad Turística");
        itemConsultaActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultaActividadActionPerformed(evt);
            }
        });
        jMenu1.add(itemConsultaActividad);

        itemConsultaPaquete.setText("Consulta de Paquete de Actividades Turísticas");
        itemConsultaPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultaPaqueteActionPerformed(evt);
            }
        });
        jMenu1.add(itemConsultaPaquete);

        itemConsultaSalida.setText("Consulta de Salida Turística");
        itemConsultaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultaSalidaActionPerformed(evt);
            }
        });
        jMenu1.add(itemConsultaSalida);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentShown

    private void itemConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaUsuarioActionPerformed
        ConsultaUsuario consultaU = new ConsultaUsuario();
        jDesktopPane1.add(consultaU);
        consultaU.setVisible(true);
        try {
            consultaU.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemConsultaUsuarioActionPerformed

    private void itemConsultaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaActividadActionPerformed

        ConsultaActividad ca = new ConsultaActividad();
        jDesktopPane1.add(ca);
        ca.setVisible(true);
        try {
            ca.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemConsultaActividadActionPerformed

    private void itemConsultaPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaPaqueteActionPerformed
        ConsultaPaqueteActividadesTuristicas ConsultaP = new ConsultaPaqueteActividadesTuristicas();
        jDesktopPane1.add(ConsultaP);
        ConsultaP.setVisible(true);
        try {
            ConsultaP.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemConsultaPaqueteActionPerformed

    private void itemConsultaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaSalidaActionPerformed
        ConsultaSalidaTur cst = new ConsultaSalidaTur();
        jDesktopPane1.add(cst);
        cst.setVisible(true);
        try {
            cst.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemConsultaSalidaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            sys.cargarDatosPrueba();
        } catch (UsuarioRepetidoException ex) {
            //Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Datos de prueba ya cargados");
            JOptionPane.showMessageDialog(null, "Datos de prueba ya cargados");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void RegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarCategoriaActionPerformed
   
    }//GEN-LAST:event_RegistrarCategoriaActionPerformed

    private void CambiarEstadoActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarEstadoActividadActionPerformed
        EstadoActTuristica aceptarAct = new EstadoActTuristica();
        jDesktopPane1.add(aceptarAct);
        aceptarAct.setVisible(true);
        try {
            aceptarAct.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_CambiarEstadoActividadActionPerformed

    private void itemModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModificarUsuarioActionPerformed
        ModificarUsuario modUsuario = new ModificarUsuario();
        jDesktopPane1.add(modUsuario);
        modUsuario.setVisible(true);
        try {
            modUsuario.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemModificarUsuarioActionPerformed

    private void itemAltaDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAltaDepartamentoActionPerformed
        AltaDepartamento dep = new AltaDepartamento();
        jDesktopPane1.add(dep);
        dep.setVisible(true);
        try {
            dep.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemAltaDepartamentoActionPerformed

    private void itemAgregarActPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarActPaqueteActionPerformed
        AgregarActividadTuristicaPaquete AgregarA = new AgregarActividadTuristicaPaquete();
        jDesktopPane1.add(AgregarA);
        AgregarA.setVisible(true);
        try {
            AgregarA.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemAgregarActPaqueteActionPerformed

    private void itemAltaPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAltaPaqueteActionPerformed
        CrearPaqueteActividades crearPaq = new CrearPaqueteActividades();
        jDesktopPane1.add(crearPaq);
        crearPaq.setVisible(true);
        try {
            crearPaq.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemAltaPaqueteActionPerformed

    private void itemInscripcionSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInscripcionSalidaActionPerformed
        InscripcionSalidaTur inscr = new InscripcionSalidaTur();
        jDesktopPane1.add(inscr);
        inscr.setVisible(true);
        try {
            inscr.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemInscripcionSalidaActionPerformed

    private void itemAltaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAltaSalidaActionPerformed
        AltaSalidaTuristica sal = new AltaSalidaTuristica();
        jDesktopPane1.add(sal);
        sal.setVisible(true);
        try {
            sal.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemAltaSalidaActionPerformed

    private void itemAltaActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAltaActividadActionPerformed
        AltaActividadTuristica ast = new AltaActividadTuristica();
        jDesktopPane1.add(ast);
        ast.setVisible(true);
        try {
            ast.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemAltaActividadActionPerformed

    private void itemAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAltaUsuarioActionPerformed
        RegistrarUsuario registro = new RegistrarUsuario();
        jDesktopPane1.add(registro);
        registro.setVisible(true);
        try {
            registro.setMaximum(true);
        } catch (Exception e) {
        }
        //registro.setMaximum(true);
    }//GEN-LAST:event_itemAltaUsuarioActionPerformed

    private void itemRegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarCategoriaActionPerformed
                //jInternalFrame1.setVisible(true);
        
        AltaCategoria categoria = new AltaCategoria();
        jDesktopPane1.add(categoria);
        categoria.setVisible(true);
        try {
            categoria.setMaximum(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_itemRegistrarCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CambiarEstadoActividad;
    private javax.swing.JMenu RegistrarCategoria;
    private javax.swing.JMenuItem itemAgregarActPaquete;
    private javax.swing.JMenuItem itemAltaActividad;
    private javax.swing.JMenuItem itemAltaDepartamento;
    private javax.swing.JMenuItem itemAltaPaquete;
    private javax.swing.JMenuItem itemAltaSalida;
    private javax.swing.JMenuItem itemAltaUsuario;
    private javax.swing.JMenuItem itemConsultaActividad;
    private javax.swing.JMenuItem itemConsultaPaquete;
    private javax.swing.JMenuItem itemConsultaSalida;
    private javax.swing.JMenuItem itemConsultaUsuario;
    private javax.swing.JMenuItem itemInscripcionSalida;
    private javax.swing.JMenuItem itemModificarUsuario;
    private javax.swing.JMenuItem itemRegistrarCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuSistema;
    // End of variables declaration//GEN-END:variables
}
