package presentacion;

import controladores.Fabrica;
import controladores.ISistema;
import controladores.Sistema;
import excepciones.UsuarioRepetidoException;
import java.awt.Image;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import logica.Usuario;
import static logica.Usuario.obtenerUsuario;



 
 
 
public class RegistrarUsuario extends javax.swing.JInternalFrame {

    public String nickname;
    public String nombre;
    public String apellido;
    public String correo;
    public LocalDate fecNac;
    public String nacionalidad;
    public String descripción;
    public String sitioWeb;
    public String imagenP;
    public String tipo;
    public String Password;

    ISistema sys;
    
    
     //Creates new form RegistrarUsuario
     
    public RegistrarUsuario() {
        initComponents();
        this.setSize(700, 700);

        jLabel10_nacionalidad.setVisible(false);
        jLabel11_descripcion.setVisible(false);
        jLabel12_sitioWeb.setVisible(false);

        txt_Descripción.setVisible(false);
        txt_SitioWeb.setVisible(false);
        txt_Nacionalidad.setVisible(false);

        jButton_RegistrarUsuario.setVisible(true);
        
        //jButton_RegistrarUsuario.setEnabled(false);

        
        jLabel_imagen.setVisible(true);

        sys = new Fabrica().getSistema();
        
        
    
        
        
        
        

    }

    
      //This method is called from within the constructor to initialize the form.
      //WARNING: Do NOT modify this code. The content of this method is always
      //regenerated by the Form Editor.
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1_Turista = new javax.swing.JRadioButton();
        jRadioButton2_Proveedor = new javax.swing.JRadioButton();
        jLabel10_nacionalidad = new javax.swing.JLabel();
        jLabel11_descripcion = new javax.swing.JLabel();
        jLabel12_sitioWeb = new javax.swing.JLabel();
        txt_Fecnac = new javax.swing.JTextField();
        txt_Nickname = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Apellido = new javax.swing.JTextField();
        txt_SitioWeb = new javax.swing.JTextField();
        txt_Correo = new javax.swing.JTextField();
        txt_Nacionalidad = new javax.swing.JTextField();
        txt_Descripción = new javax.swing.JTextField();
        jButton_RegistrarUsuario = new javax.swing.JButton();
        jLabel1_ERROR = new javax.swing.JLabel();
        jButton_imagen = new javax.swing.JButton();
        jLabel_imagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nickname:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel6.setText("Apellido:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel7.setText("Fecha de Nacimiento (año-mes-dia):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel8.setText("Correo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel9.setText("Tipo de Usuario:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        buttonGroup1.add(jRadioButton1_Turista);
        jRadioButton1_Turista.setText("Turista");
        jRadioButton1_Turista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1_TuristaActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1_Turista, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        buttonGroup1.add(jRadioButton2_Proveedor);
        jRadioButton2_Proveedor.setText("Proveedor");
        jRadioButton2_Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2_ProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2_Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel10_nacionalidad.setText("Nacionalidad:");
        getContentPane().add(jLabel10_nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel11_descripcion.setText("Descripción:");
        getContentPane().add(jLabel11_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel12_sitioWeb.setText("Sitio Web:");
        getContentPane().add(jLabel12_sitioWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        txt_Fecnac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FecnacActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Fecnac, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 150, -1));

        txt_Nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NicknameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 270, -1));

        txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 270, -1));

        txt_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 270, -1));

        txt_SitioWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SitioWebActionPerformed(evt);
            }
        });
        getContentPane().add(txt_SitioWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 270, -1));

        txt_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 270, -1));

        txt_Nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NacionalidadActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 270, -1));

        txt_Descripción.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DescripciónActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Descripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 270, -1));

        jButton_RegistrarUsuario.setText("Registrar Usuario");
        jButton_RegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 220, -1));
        getContentPane().add(jLabel1_ERROR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 410, 20));

        jButton_imagen.setText("Seleccionar Imagen");
        jButton_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_imagenActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));
        getContentPane().add(jLabel_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 150, 130));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1_TuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1_TuristaActionPerformed

        if (jRadioButton1_Turista.isSelected() == true) {

            jLabel10_nacionalidad.setVisible(true);
            jLabel11_descripcion.setVisible(false);
            jLabel12_sitioWeb.setVisible(false);
            txt_Nacionalidad.setVisible(true);
            txt_Descripción.setVisible(false);
            txt_SitioWeb.setVisible(false);

        }

    }//GEN-LAST:event_jRadioButton1_TuristaActionPerformed

    private void jRadioButton2_ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2_ProveedorActionPerformed

        if (jRadioButton2_Proveedor.isSelected() == true) {

            jLabel10_nacionalidad.setVisible(false);
            jLabel11_descripcion.setVisible(true);
            txt_Descripción.setVisible(true);
            jLabel12_sitioWeb.setVisible(true);
            txt_SitioWeb.setVisible(true);
            txt_Nacionalidad.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton2_ProveedorActionPerformed

    private void txt_FecnacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FecnacActionPerformed

        fecNac = LocalDate.parse(txt_Fecnac.getText());
       
    }//GEN-LAST:event_txt_FecnacActionPerformed

    private void txt_NicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NicknameActionPerformed

        nickname = txt_Nickname.getText();
        
    }//GEN-LAST:event_txt_NicknameActionPerformed

    private void txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreActionPerformed
        nombre = txt_Nombre.getText();
        
    }//GEN-LAST:event_txt_NombreActionPerformed

    private void txt_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoActionPerformed
        apellido = txt_Apellido.getText();
        
    }//GEN-LAST:event_txt_ApellidoActionPerformed

    private void txt_SitioWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SitioWebActionPerformed
        sitioWeb = txt_SitioWeb.getText();
       
    }//GEN-LAST:event_txt_SitioWebActionPerformed

    private void txt_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CorreoActionPerformed
        correo = txt_Correo.getText();
       
    }//GEN-LAST:event_txt_CorreoActionPerformed

    private void txt_NacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NacionalidadActionPerformed
        nacionalidad = txt_Nacionalidad.getText();
        
    }//GEN-LAST:event_txt_NacionalidadActionPerformed

    private void txt_DescripciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DescripciónActionPerformed
        descripción = txt_Descripción.getText();
        
    }//GEN-LAST:event_txt_DescripciónActionPerformed

   
    private void jButton_RegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarUsuarioActionPerformed

    nickname = txt_Nickname.getText();
    nombre = txt_Nombre.getText();
    apellido = txt_Apellido.getText();
    correo = txt_Correo.getText();
    Password="123";

    try {
        
        // Validación de campos obligatorios
        if (nickname.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || correo.isEmpty()) {
            throw new IllegalArgumentException("ERROR: faltan campos por completar.");
        }

        // Validación de fecha de nacimiento
        fecNac = LocalDate.parse(txt_Fecnac.getText());

        if (!jRadioButton1_Turista.isSelected() && !jRadioButton2_Proveedor.isSelected()) {
            throw new IllegalArgumentException("ERROR: Seleccione Tipo de Usuario");
        }

        if (jRadioButton1_Turista.isSelected()) {
            nacionalidad = txt_Nacionalidad.getText();
            descripción = null;
            sitioWeb = null;
            tipo="turista";

            // Validación de nacionalidad si es turista
            if (nacionalidad.isEmpty()) {
                throw new IllegalArgumentException("ERROR: faltan campos por completar.");
            }
        } else if (jRadioButton2_Proveedor.isSelected()) {
            descripción = txt_Descripción.getText();
            sitioWeb = txt_SitioWeb.getText();
            nacionalidad = null;
            tipo="proveedor";

            // Validación de descripción y sitio web si es proveedor
            if (descripción.isEmpty() || sitioWeb.isEmpty()) {
                throw new IllegalArgumentException("ERROR: faltan campos por completar.");
            }
        }

        // Llamar a sys.registrarUsuario solo si no se lanzó ninguna excepción
        sys.registrarUsuario(nickname, nombre, apellido, correo, fecNac, tipo, nacionalidad, descripción, sitioWeb,imagenP, Password);
        jLabel1_ERROR.setText("Usuario registrado con éxito.");
        imagenP=null;
        jLabel_imagen.setVisible(false);
    } catch (DateTimeParseException e) {
        jLabel1_ERROR.setText("ERROR: fecha inválida. Use el formato YYYY-MM-DD.");
    } catch (IllegalArgumentException e) {
        jLabel1_ERROR.setText(e.getMessage());
    } catch (UsuarioRepetidoException e) {
        jLabel1_ERROR.setText("Error al registrar el usuario: " + e.getMessage());
    }
  
    }//GEN-LAST:event_jButton_RegistrarUsuarioActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        dispose();
    }   
    /*
    private void jButton_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_imagenActionPerformed
        
    JFileChooser fileChooser = new JFileChooser(new File(System.getProperty("user.home") + "/Desktop/fotos"));
    
    int result = fileChooser.showOpenDialog(this);
    
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();
        imagenP = selectedFile.getAbsolutePath();
        // Puedes mostrar la ruta de la imagen en algún campo de texto o etiqueta para que el usuario la vea
        // Por ejemplo: txt_RutaImagen.setText(imagenP);
        // También puedes cargar la imagen en un componente de vista previa si lo deseas.
    }
        
    }//GEN-LAST:event_jButton_imagenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    */
    
    
    /*
    private void jButton_imagenActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
        JFileChooser jFileChooser = new JFileChooser();
        
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JPG & PNG","jpg","png");
        
        jFileChooser.setFileFilter(filtrado);
        
        int respuesta = jFileChooser.showOpenDialog(this);
        
        if(respuesta == JFileChooser.APPROVE_OPTION){
        
            imagenP= jFileChooser.getSelectedFile().getPath();
            
                   
            ImageIcon imagenIcon = new ImageIcon(imagenP);
            jLabel_imagen.setIcon(imagenIcon);
        
        
            jLabel_imagen.setSize(imagenIcon.getIconWidth(), imagenIcon.getIconHeight());
            
        }
        
    } 
    
    */
 
    
        private void jButton_imagenActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
        JFileChooser jFileChooser = new JFileChooser();
        
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JPG & PNG","jpg","png");
        
        jFileChooser.setFileFilter(filtrado);
        
        int respuesta = jFileChooser.showOpenDialog(this);
        
        if(respuesta == JFileChooser.APPROVE_OPTION){
        
            imagenP= jFileChooser.getSelectedFile().getPath();
             
            Image mImagen = new ImageIcon(imagenP).getImage();
            
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(jLabel_imagen.getWidth(),jLabel_imagen.getHeight(), Image.SCALE_SMOOTH));
           
            jLabel_imagen.setIcon(mIcono);
            
            jLabel_imagen.setVisible(true);
            
        }
        
    } 
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_RegistrarUsuario;
    private javax.swing.JButton jButton_imagen;
    private javax.swing.JLabel jLabel10_nacionalidad;
    private javax.swing.JLabel jLabel11_descripcion;
    private javax.swing.JLabel jLabel12_sitioWeb;
    private javax.swing.JLabel jLabel1_ERROR;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_imagen;
    private javax.swing.JRadioButton jRadioButton1_Turista;
    private javax.swing.JRadioButton jRadioButton2_Proveedor;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_Descripción;
    private javax.swing.JTextField txt_Fecnac;
    private javax.swing.JTextField txt_Nacionalidad;
    private javax.swing.JTextField txt_Nickname;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_SitioWeb;
    // End of variables declaration//GEN-END:variables

}

